# About Dot Product
(Asking the same thing in different ways)
1.   What is the meaning of dot product?
2.   Why do we do dot product?
3.   When do we use dot product?
4.   When can we use dot product?(and when can't we use it?)

# Task

1.   Generate 2 random matrices of 5x5 size
2.   Do dot product

# Question
Given a matrix $\textbf{A}$ defined as 

$\textbf{A} =\begin{bmatrix}
    a & b  \\
    c & d  \\
\end{bmatrix}$


where $∀i \in \textbf{E}=\{a,b,c,d\}$,  $i$ is a unique value, how can we generate a symmetric matrix using only $\textbf{A}$? 



# Basic numpy

1. Play around with numpy -there are many tutorials that you can google it.
2. Comfortable enough with arrays, list,
indexing, access elements, how to reassign values.
3. For loops with arrays.
4. Can create functions( take input parameters, return a value)
5. List comprehension, very convenient.



In [1]:
import numpy as np

arr = np.array([1,2,3]) # create 1-dimensional array

print(arr) # print the array

arr2d = np.array([[1,2,3], [4,5,6]]) # create 2-dimensional array

print(arr2d) # print the array

print('--for loops by rows here---')
for item in arr2d:
    print('item: ', item)
# there is much better ways of doing this 

# Function
def addition(x,y):
    return x*y

print('3*2 is ', addition(3,2))

[1 2 3]
[[1 2 3]
 [4 5 6]]
--for loops by rows here---
item:  [1 2 3]
item:  [4 5 6]
3*2 is  6


# Summation of array

In [2]:
arr = np.random.rand(3)
print('array: ', arr, 'sum of array: ', arr.sum())

array:  [0.22023007 0.61677041 0.57495194] sum of array:  1.4119524195334694


# Transpose, dot product
1. Randomly initialize two vectors **a** and **b** of the same dimension
2. Perform dot product c = **a.b**

# Matrix multiplication
1. Randomly initialize two matrices **A** and **B** of the same (inner) dimension
2. Perform matrix multiplication  **AB** and **BA** (when is this possible?)
3. Does **AB**= **BA**? If not, how do we set so that **AB**= **BA**?


In [3]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[4,5,6],[7,8,9]])

print("c = a.b : c = ", a*b)

# Matrix multiplication

AB = a*b
BA = b*a

print("A*B = ", AB)
print("B*A = ", BA)
print(AB == BA)

c = a.b : c =  [[ 4 10 18]
 [28 40 54]]
A*B =  [[ 4 10 18]
 [28 40 54]]
B*A =  [[ 4 10 18]
 [28 40 54]]
[[ True  True  True]
 [ True  True  True]]


# Random seed

For reproducibility. Pseudo random generators are not actually random, but deterministic in a sense. 

In [4]:
import random

random.seed(5)
print(random.random())

print("--------")
for i in range(11):
    random.seed(i)
    print(random.random())

0.6229016948897019
--------
0.8444218515250481
0.13436424411240122
0.9560342718892494
0.23796462709189137
0.23604808973743452
0.6229016948897019
0.793340083761663
0.32383276483316237
0.2267058593810488
0.46300735781502145
0.5714025946899135


# Torch exercise 
-To change the shape of an array in torch/tensor, use view and re assign the variable. view() is like np.reshape() 


In [5]:
import torch

print("\n---A 4x4 tensor----\n")
a = torch.rand(4,4)
print(a)

print("\n---Reshaped tensor to 8x2----\n")
a = a.view(8,2)
print(a)

print("\n---Flattens the tensor into a vector----\n")
a = a.view(-1)
print(a)


---A 4x4 tensor----

tensor([[0.2782, 0.9502, 0.2412, 0.5095],
        [0.3850, 0.5824, 0.7950, 0.7165],
        [0.1554, 0.6570, 0.5937, 0.0567],
        [0.4868, 0.8219, 0.6809, 0.3627]])

---Reshaped tensor to 8x2----

tensor([[0.2782, 0.9502],
        [0.2412, 0.5095],
        [0.3850, 0.5824],
        [0.7950, 0.7165],
        [0.1554, 0.6570],
        [0.5937, 0.0567],
        [0.4868, 0.8219],
        [0.6809, 0.3627]])

---Flattens the tensor into a vector----

tensor([0.2782, 0.9502, 0.2412, 0.5095, 0.3850, 0.5824, 0.7950, 0.7165, 0.1554,
        0.6570, 0.5937, 0.0567, 0.4868, 0.8219, 0.6809, 0.3627])


In [7]:

import numpy as np

X = np.array([[-1, -1], [-1, 1], [1, 1], [1, -1]])
print(X)

[[-1 -1]
 [-1  1]
 [ 1  1]
 [ 1 -1]]
